export const INVITATIONINPUTCHANGE = "INVITATIONINPUTCHANGE"
export const SETMEETINGDATE = "SETMEETINGDATE"
export const SETMEETINGTIME = "SETMEETINGTIME"

export const CONTACTINPUTCHANGE = "CONTACTINPUTCHANGE"
export const SETCONTACT = "SETCONTACT"

export const SIGNUPINPUTCHANGE = "SIGNUPINPUTCHANGE"
export const SIGNININPUTCHANGE = "SIGNININPUTCHANGE"
export const SETLOGINMODE = "SETLOGINMODE"
export const SETUSERID = "SETUSERID"


export const MOBILECHANGEINPUT = "MOBILECHANGEINPUT"
export const VERIFYCHANGEINPUT = "VERIFYCHANGEINPUT"

export const SWITCHFORM = "SWITCHFORM"

export const GETMEETINGS = "GETMEETINGS"
export const GETCONTACTS = "GETCONTACTS"
