export const INVITATIONINPUTCHANGE = 'INVITATIONINPUTCHANGE'
export const SETMEETINGDATE = 'SETMEETINGDATE'
export const SETMEETINGTIME = 'SETMEETINGTIME'

export const CONTACTINPUTCHANGE = 'CONTACTINPUTCHANGE'
export const SETCONTACT = "SETCONTACT"

export const SIGNINCHANGEINPUT = "SIGNINCHANGEINPUT"

export const SWITCHFORM = "SWITCHFORM"


export const GETMEETINGS = 'GETMEETINGS'
export const GETCONTACTS = "GETCONTACTS"