export const INVITATIONINPUTCHANGE = 'INVITATIONINPUTCHANGE'
export const SETMEETINGDATE = 'SETMEETINGDATE'
export const GETMEETINGS = 'GETMEETINGS'
export const CONTACTINPUTCHANGE = 'CONTACTINPUTCHANGE'
export const GETCONTACTS = "GETCONTACTS"